### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by dinosauria123** [daleyjem/ustvnow-firetv#1]
I have installed your apk file to my FireTV stick.
I could see EPG after logging in, but I can not play any TV streams...

**Comment by daleyjem** [comment]
@dinosauria123 Sorry, what is EPG? Also, are you able to play those same streams fine through your browser on USTVNow's website?

**Comment by dinosauria123** [comment]
Thank you for your quick reply.

EPG means your screen shot of the top page.
https://github.com/daleyjem/ustvnow-firetv/blob/master/screenshot.png

I can play USTVNow through my browser on PC (I'm living in Japan, but no problem to watch the stream of USTVNow on FireFox).

I could choose TV programs and could see playback controls on FireTV, but when I choose play I could see black screen only, no TV streams.

I use Japanese version of FireTV OS.

**Comment by daleyjem** [comment]
Hmm. May be a little difficult for me to test with your particular set up. I'm not having any issues on my end. Do you have any developer experience... particularly debugging in Javascript?

If you can `adb connect` to your FireTV and then inspect the page with this ADB Chrome extension (https://chrome.google.com/webstore/detail/adb/dpngiggdglpdnjdoaefidgiigpemgage?hl=en-US), maybe you can offer some help to track down the issue.

**Comment by dinosauria123** [comment]
Thank you for the info.

I'm not familiar to Javascript. I tried to install your Chrome plugin on my PC, but I could not find my  fireTVStick.
How is the port number ? (5555?)

I use FireTVStick 1st Gen, FireOS 5.2.1.2 (562254320). How about you ?
I could play USTVNow on my FireTVStick using Chrome browser for android.

**Comment by daleyjem** [comment]
Have you tried pressing the ◄◄ button on the remote? It loops through different qualities: "auto", "high", "medium" and "low" quality.

**Comment by dinosauria123** [comment]
Yes, Mothing change. Still black screen...

**Comment by daleyjem** [comment]
Man, I'm sorry... but I can't honestly think of how to troubleshoot your issue without more in-depth "developer" feedback of what the cause is =/

**Comment by daleyjem** [comment]
Can you tell me what your country settings are? You can see what it's currently set to here:
https://www.amazon.com/mn/dcw/myx.html#/home/settings/payment

Also, what is your device's Timezone set to? You can see what that is on your FireTV under Settings -> System.

I'm curious if your issue is related to either of those things.

Before any of that though... I pushed a new APK file. Can you try installing that and see if anything changes?

**Comment by dinosauria123** [comment]
Thank you for making new apk and inform me.

I have tried your new apk file, but I can get black screen.

Next I did factory reset and re-set up my FireTV Stick using English (US) and newly created US Amazon Account (not Japanese account).

But I got brack screen and no TV streams.

I began to thinking it is due to hardware of the FireTV Stick 1st gen. It does not decord some video file format.

I try to use your apk on my android tablet (Amazon Fire 2015) I can watch TV stream ! It is interesting.

**Comment by daleyjem** [comment]
Hmm, that is interesting. I thought I had a gen 1 also, but perhaps not. My software version is 5.2.1.2. Model number of the device is W87CUN.

Since you reset, did you also do a manual update check? I'm curious which version you're on.

**Comment by dinosauria123** [comment]
Thank you for your reply.
My FireOS is 5.2.1.2. I will check my model number later.

**Comment by dinosauria123** [comment]
My FireTV stick is also W87CUN, write on the back of the stick.

More information from the serial number as shown here.

http://www.aftvnews.com/serial/

Rootable: No, All Fire TV Sticks cannot be rooted
Likely Software Version: Unknown (Data for the Fire TV Stick is not available
Manufactured: By Foxconn on 10/16/2015
Hardware Revision: 05
Unit Revision: 04
Condition (New or Refurbished): New
Note: This information may not be entirely accurate. Especially with recently manufactured devices.

My FireTV Stick is seems to the same as yours. I am confusing why I can not play any streams...

**Comment by daleyjem** [comment]
Believe me, I'm as confused as you are. Because you can view things on your tablet however makes me somewhat optimistic. Do you have a friend with a newer gen model to at least see if it works on theirs? =/

**Comment by dinosauria123** [comment]
I have uploaded how it works on my FireTV Stick. I hope it something helps.

https://youtu.be/6u5G8vVIpi0

**Comment by dinosauria123** [comment]
I bought new FireTV Stick (2nd Gen.) from B&H because it can not buy in Japan.

Unfortunately, video does not playing on 2nd Gen. FireTV Stick.

I tried video playing out of my house (I went to trip, the hotel I stayed has wireless LAN) ,
video does not playing at the hotel.

I think this problem come from my living country (Japan), not come from FireTV Stick hardware and
my network connection....

**Comment by Gulfbreeze** [comment]
@dinosauria123 @daleyjem,  Your problem is **NOT** with the Apk, it works perfectly. 

I was having same issue, found out that after **45 days,** they (**_USTV NOW_**) switch from **HD** back to **SD** for the **FREE ACCOUNTS
![ustv](https://cloud.githubusercontent.com/assets/26692324/24333195/30082fca-1219-11e7-9737-f130feae3cd6.jpg)
**.  

This Apk works perfectly, if you upgrade to the **All Channels packages** (both with and without the DVR service). 

Maybe we can get @daleyjem, to allow for **both SD & HD** broadcast so we don't keep having to create new accounts every 45 days.....**Please Sir!**

**Comment by dinosauria123** [comment]
Dear Gulfbreeze,
Thank  you, you are right !

I made another USTVNow account and logged in new account, I can watch the TV programs !

I think it is due to User Agent of the application. If we set the UA as SmartPhone, we could see the TV program even in the free account.

Thanks lot ! I will wait next update !

**Comment by daleyjem** [comment]
I'll take another look at it when I have the time. Since I cancelled my paid account, maybe I can then troubleshoot the issue you're having with the free account.

**Comment by dinosauria123** [comment]
Thank you for back and answer to us.
Your apk is great, I am now enjoying US TV programs in Japan !

**Comment by Gulfbreeze** [comment]
*USTVnow 3rd Party Device Support
<https://support.ustvnow.com/hc/en-us/articles/214145843>*

*NOTE: * Although many users watch our service with Android boxes, we do
not provide technical and customer support for them and 3rd party plugins
such as XMBC/Kodi.

*If you are on the free plan, after 45 days you will be able to watch
USTVnow only on a computer.*
