### ISSUE TITLE
Ustvnow Login issue

### ISSUE THREAD

**Issue by Gulfbreeze** [daleyjem/ustvnow-firetv#2]
The app kind of stopped working.
I can get to the Log-in page, I enter the login details (Email & password) it shows the title screen,
then begins flashing. No picture or audio just flashing.  Not real sure what the hic-up
may be this time. But figured I'd let you know about it.

Gulfbreeze

**Comment by ahajinikitas** [comment]
Same issue. . . both with downloaded APK and building from source.

**Comment by daleyjem** [comment]
The latest push should resolve this

**Comment by ahajinikitas** [comment]
Confirmed, operational 👍 Thank you so much!

**Comment by daleyjem** [comment]
Excellent! Thanks for confirming, @ahajinikitas
